package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador", schema = "public")
public class Administrador implements java.io.Serializable {

	private int codAdministrador;
	private Usuario usuario;

	public Administrador() {
	}

	public Administrador(int codAdministrador) {
		this.codAdministrador = codAdministrador;
	}

	public Administrador(int codAdministrador, Usuario usuario) {
		this.codAdministrador = codAdministrador;
		this.usuario = usuario;
	}

	@Id

	@Column(name = "cod_administrador", unique = true, nullable = false)
	public int getCodAdministrador() {
		return this.codAdministrador;
	}

	public void setCodAdministrador(int codAdministrador) {
		this.codAdministrador = codAdministrador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
