package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", schema = "public")
public class Categoria implements java.io.Serializable {

	private int codCategoria;
	private String nomCategoria;
	private Integer costoCategoria;
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public Categoria() {
	}

	public Categoria(int codCategoria) {
		this.codCategoria = codCategoria;
	}

	public Categoria(int codCategoria, String nomCategoria, Integer costoCategoria, Set<Factura> facturas) {
		this.codCategoria = codCategoria;
		this.nomCategoria = nomCategoria;
		this.costoCategoria = costoCategoria;
		this.facturas = facturas;
	}

	@Id

	@Column(name = "cod_categoria", unique = true, nullable = false)
	public int getCodCategoria() {
		return this.codCategoria;
	}

	public void setCodCategoria(int codCategoria) {
		this.codCategoria = codCategoria;
	}

	@Column(name = "nom_categoria")
	public String getNomCategoria() {
		return this.nomCategoria;
	}

	public void setNomCategoria(String nomCategoria) {
		this.nomCategoria = nomCategoria;
	}

	@Column(name = "costo_categoria")
	public Integer getCostoCategoria() {
		return this.costoCategoria;
	}

	public void setCostoCategoria(Integer costoCategoria) {
		this.costoCategoria = costoCategoria;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "categorias")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
