package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name = "clase", schema = "public")
public class Clase implements java.io.Serializable {

	private int codClase;
	private Horario horario;
	private Profesor profesor;
	private Ritmo ritmo;
	private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);
	private Set<Reporte> reportes = new HashSet<Reporte>(0);

	public Clase() {
	}

	public Clase(int codClase) {
		this.codClase = codClase;
	}

	public Clase(int codClase, Horario horario, Profesor profesor, Ritmo ritmo, Set<Estudiante> estudiantes,
			Set<Reporte> reportes) {
		this.codClase = codClase;
		this.horario = horario;
		this.profesor = profesor;
		this.ritmo = ritmo;
		this.estudiantes = estudiantes;
		this.reportes = reportes;
	}

	@Id

	@Column(name = "cod_clase", unique = true, nullable = false)
	public int getCodClase() {
		return this.codClase;
	}

	public void setCodClase(int codClase) {
		this.codClase = codClase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_horario")
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_profesor")
	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_ritmo")
	public Ritmo getRitmo() {
		return this.ritmo;
	}

	public void setRitmo(Ritmo ritmo) {
		this.ritmo = ritmo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "detalle_clase", schema = "public", joinColumns = {
			@JoinColumn(name = "cod_clase", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "cod_estudiante", nullable = false, updatable = false) })
	public Set<Estudiante> getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Set<Estudiante> estudiantes) {
		this.estudiantes = estudiantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clase")
	public Set<Reporte> getReportes() {
		return this.reportes;
	}

	public void setReportes(Set<Reporte> reportes) {
		this.reportes = reportes;
	}

}
