package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", schema = "public")
public class Empleado implements java.io.Serializable {

	private int codEmpleado;
	private Usuario usuario;

	public Empleado() {
	}

	public Empleado(int codEmpleado) {
		this.codEmpleado = codEmpleado;
	}

	public Empleado(int codEmpleado, Usuario usuario) {
		this.codEmpleado = codEmpleado;
		this.usuario = usuario;
	}

	@Id

	@Column(name = "cod_empleado", unique = true, nullable = false)
	public int getCodEmpleado() {
		return this.codEmpleado;
	}

	public void setCodEmpleado(int codEmpleado) {
		this.codEmpleado = codEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
