package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiante generated by hbm2java
 */
@Entity
@Table(name = "estudiante", schema = "public")
public class Estudiante implements java.io.Serializable {

	private int codEstudiante;
	private Usuario usuario;
	private String nombreAcudiente;
	private String correoAcudiente;
	private Set<Clase> clases = new HashSet<Clase>(0);
	private Set<Factura> facturas = new HashSet<Factura>(0);
	private Set<Reporte> reportes = new HashSet<Reporte>(0);

	public Estudiante() {
	}

	public Estudiante(int codEstudiante) {
		this.codEstudiante = codEstudiante;
	}

	public Estudiante(int codEstudiante, Usuario usuario, String nombreAcudiente, String correoAcudiente,
			Set<Clase> clases, Set<Factura> facturas, Set<Reporte> reportes) {
		this.codEstudiante = codEstudiante;
		this.usuario = usuario;
		this.nombreAcudiente = nombreAcudiente;
		this.correoAcudiente = correoAcudiente;
		this.clases = clases;
		this.facturas = facturas;
		this.reportes = reportes;
	}

	@Id

	@Column(name = "cod_estudiante", unique = true, nullable = false)
	public int getCodEstudiante() {
		return this.codEstudiante;
	}

	public void setCodEstudiante(int codEstudiante) {
		this.codEstudiante = codEstudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre_acudiente")
	public String getNombreAcudiente() {
		return this.nombreAcudiente;
	}

	public void setNombreAcudiente(String nombreAcudiente) {
		this.nombreAcudiente = nombreAcudiente;
	}

	@Column(name = "correo_acudiente")
	public String getCorreoAcudiente() {
		return this.correoAcudiente;
	}

	public void setCorreoAcudiente(String correoAcudiente) {
		this.correoAcudiente = correoAcudiente;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "estudiantes")
	public Set<Clase> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clase> clases) {
		this.clases = clases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiante")
	public Set<Reporte> getReportes() {
		return this.reportes;
	}

	public void setReportes(Set<Reporte> reportes) {
		this.reportes = reportes;
	}

}
