package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "factura", schema = "public")
public class Factura implements java.io.Serializable {

	private int codFactura;
	private Estudiante estudiante;
	private Date fechaFactura;
	private Integer valFactura;
	private Set<Categoria> categorias = new HashSet<Categoria>(0);

	public Factura() {
	}

	public Factura(int codFactura) {
		this.codFactura = codFactura;
	}

	public Factura(int codFactura, Estudiante estudiante, Date fechaFactura, Integer valFactura,
			Set<Categoria> categorias) {
		this.codFactura = codFactura;
		this.estudiante = estudiante;
		this.fechaFactura = fechaFactura;
		this.valFactura = valFactura;
		this.categorias = categorias;
	}

	@Id

	@Column(name = "cod_factura", unique = true, nullable = false)
	public int getCodFactura() {
		return this.codFactura;
	}

	public void setCodFactura(int codFactura) {
		this.codFactura = codFactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_estudiante")
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_factura", length = 13)
	public Date getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura(Date fechaFactura) {
		this.fechaFactura = fechaFactura;
	}

	@Column(name = "val_factura")
	public Integer getValFactura() {
		return this.valFactura;
	}

	public void setValFactura(Integer valFactura) {
		this.valFactura = valFactura;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "detalle_factura", schema = "public", joinColumns = {
			@JoinColumn(name = "cod_factura", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "cod_categoria", nullable = false, updatable = false) })
	public Set<Categoria> getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Set<Categoria> categorias) {
		this.categorias = categorias;
	}

}
