package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario", schema = "public")
public class Horario implements java.io.Serializable {

	private int codHorario;
	private Date horaInicio;
	private Date horaFinal;
	private Set<Clase> clases = new HashSet<Clase>(0);

	public Horario() {
	}

	public Horario(int codHorario) {
		this.codHorario = codHorario;
	}

	public Horario(int codHorario, Date horaInicio, Date horaFinal, Set<Clase> clases) {
		this.codHorario = codHorario;
		this.horaInicio = horaInicio;
		this.horaFinal = horaFinal;
		this.clases = clases;
	}

	@Id

	@Column(name = "cod_horario", unique = true, nullable = false)
	public int getCodHorario() {
		return this.codHorario;
	}

	public void setCodHorario(int codHorario) {
		this.codHorario = codHorario;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", length = 15)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_final", length = 15)
	public Date getHoraFinal() {
		return this.horaFinal;
	}

	public void setHoraFinal(Date horaFinal) {
		this.horaFinal = horaFinal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<Clase> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clase> clases) {
		this.clases = clases;
	}

}
