package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements java.io.Serializable {

	private int codPerfil;
	private String nomPerfil;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Perfil() {
	}

	public Perfil(int codPerfil) {
		this.codPerfil = codPerfil;
	}

	public Perfil(int codPerfil, String nomPerfil, Set<Usuario> usuarios) {
		this.codPerfil = codPerfil;
		this.nomPerfil = nomPerfil;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "cod_perfil", unique = true, nullable = false)
	public int getCodPerfil() {
		return this.codPerfil;
	}

	public void setCodPerfil(int codPerfil) {
		this.codPerfil = codPerfil;
	}

	@Column(name = "nom_perfil")
	public String getNomPerfil() {
		return this.nomPerfil;
	}

	public void setNomPerfil(String nomPerfil) {
		this.nomPerfil = nomPerfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
