package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Reporte generated by hbm2java
 */
@Entity
@Table(name = "reporte", schema = "public")
public class Reporte implements java.io.Serializable {

	private int codReporte;
	private Clase clase;
	private Estudiante estudiante;
	private Profesor profesor;
	private String observacion;

	public Reporte() {
	}

	public Reporte(int codReporte) {
		this.codReporte = codReporte;
	}

	public Reporte(int codReporte, Clase clase, Estudiante estudiante, Profesor profesor, String observacion) {
		this.codReporte = codReporte;
		this.clase = clase;
		this.estudiante = estudiante;
		this.profesor = profesor;
		this.observacion = observacion;
	}

	@Id

	@Column(name = "cod_reporte", unique = true, nullable = false)
	public int getCodReporte() {
		return this.codReporte;
	}

	public void setCodReporte(int codReporte) {
		this.codReporte = codReporte;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_clase")
	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_estudiante")
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_profesor")
	public Profesor getProfesor() {
		return this.profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
