package entidad;
// Generated 22/04/2018 07:09:53 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ritmo generated by hbm2java
 */
@Entity
@Table(name = "ritmo", schema = "public")
public class Ritmo implements java.io.Serializable {

	private int codRitmo;
	private String nomRitmo;
	private Set<Clase> clases = new HashSet<Clase>(0);

	public Ritmo() {
	}

	public Ritmo(int codRitmo) {
		this.codRitmo = codRitmo;
	}

	public Ritmo(int codRitmo, String nomRitmo, Set<Clase> clases) {
		this.codRitmo = codRitmo;
		this.nomRitmo = nomRitmo;
		this.clases = clases;
	}

	@Id

	@Column(name = "cod_ritmo", unique = true, nullable = false)
	public int getCodRitmo() {
		return this.codRitmo;
	}

	public void setCodRitmo(int codRitmo) {
		this.codRitmo = codRitmo;
	}

	@Column(name = "nom_ritmo")
	public String getNomRitmo() {
		return this.nomRitmo;
	}

	public void setNomRitmo(String nomRitmo) {
		this.nomRitmo = nomRitmo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ritmo")
	public Set<Clase> getClases() {
		return this.clases;
	}

	public void setClases(Set<Clase> clases) {
		this.clases = clases;
	}

}
